server:
  port: 8888 
  

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"      

info:
  app: 
    name: @project.artifactId@
    description: "TinkerForge Weather Station"
    version: @project.version@

weatherstation:
  position:
    altitude: 25
    latitude: 53.98465878500624
    longitude: 12.183633460018223
  mode:
    nightmode: true
    alarmfashing: true

openweather:
  enable: true
  station_id: 5df37e046c634e00011dff22
  #APPID: XXXX write openweateher appid int ENV
  # Spring Boot will read the ENV  
  #export OPENWEATHER_APPID=cacsscgsvgdv
