server:
  port: 8888 
  

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"      

info:
  app: 
    name: @project.artifactId@
    description: "TinkerForge Weather Station"
    version: @project.version@

weatherstation:
  position:
    altitude: 25
    latitude: 53.98465878500624
    longitude: 12.183633460018223
  mode:
    nightmode: true

