server:
  port: 8888 
  

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"      

info:
  app: 
    name: @project.artifactId@
    description: "TinkerForge Weather Station"
    version: @project.version@


