server:
  port: 8888 
  
spring:
  freemarker:
    enabled: false
  jmx:
    enabled: false
  groovy:
    template:
      enabled: false

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"      

info:
  app: 
    name: "@project.artifactId@"
    description: "TinkerForge Weather Station"
    version: "@project.version@"

weatherstation:
  position:
    altitude: 25
    latitude: 53.98465878500624
    longitude: 12.183633460018223
  mode:
    nightmode: true
    alarmfashing: true

tinkerforge:
  enable: true
  
openweather:
  enable: true
  send: true
  station_id: 5df37e046c634e00011dff22
  #APPID: XXXX write openweateher appid int ENV
  # Spring Boot will read the ENV  
  #export OPENWEATHER_APPID=cacsscgsvgdv

  
---

spring:
  profiles: test

weatherstation:
  mode:
    nightmode: false

tinkerforge:
  enable: false
  
openweather:
  enable: true
  send: false
  station_id: 5df37e046c634e00011dff22
  APPID: XXXX
